// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeM9Y_LwQBbKTfaWPi64EG_R5mg2bA2pc',
    appId: '1:249328358820:web:a3657cd0ed63b44167dd31',
    messagingSenderId: '249328358820',
    projectId: 'infoquario',
    authDomain: 'infoquario.firebaseapp.com',
    storageBucket: 'infoquario.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLnhqZc1_NkJzIYLppaNO7UzJLCDJzpu8',
    appId: '1:249328358820:android:c7b4c75c9205ba7d67dd31',
    messagingSenderId: '249328358820',
    projectId: 'infoquario',
    storageBucket: 'infoquario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5h_fNESQSMldlRxuRoXrdoolCzwk6Mj0',
    appId: '1:249328358820:ios:f68cafe27cf8a93667dd31',
    messagingSenderId: '249328358820',
    projectId: 'infoquario',
    storageBucket: 'infoquario.appspot.com',
    iosClientId: '249328358820-edv5eho25mkkp4rnjnkf5pv5s8slnsbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
